[ly.synced-apple.com]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://itunes.apple.com/search?term=%artist%%20%title%&entity=song&limit=3
SearchQueryEncoding=URL
SearchResult.StartTags="results":[
SearchResult.FinishTags=]}
SearchResultArtist.StartTags="artistName":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="trackName":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="trackId":"
SearchResultURL.FinishTags=",
SearchResultURL.PostProcessExpression=https://lyrics.paxsenix.org/apple-music/lyrics?id=%Value
DataLyrics.StartTags="lrc":"
DataLyrics.FinishTags=",
DataLyrics.PostProcessExpression=%IFGreater(%Length(%Value),28,%Value,)

[ly.synced-deezer.com]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://api.deezer.com/search/track?limit=3&q=%artist%%20%title%
SearchQueryEncoding=URL
SearchResult.StartTags="data":[
SearchResult.FinishTags=],
SearchResultArtist.StartTags="artist":{|"name":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="title":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="id":
SearchResultURL.FinishTags=,
SearchResultURL.PostProcessExpression=https://andrechris24.serv00.net/deezer/%Value
DataLyrics.StartTags="synced":"
DataLyrics.FinishTags=",
DataLyrics.PostProcessExpression=%IFGreater(%Length(%Value),28,%Value,)

[ly.synced-lrclib.net]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://lrclib.net/api/search?artist_name=%artist%&track_name=%title%
SearchQueryEncoding=URL
SearchResultMaxCount=5
SearchResult.StartTags=[
SearchResult.FinishTags=]
SearchResultArtist.StartTags="artistName":"
SearchResultArtist.FinishTags="
SearchResultTitle.StartTags="trackName":"
SearchResultTitle.FinishTags="
SearchResultURL.StartTags="id":
SearchResultURL.FinishTags=,
SearchResultURL.PostProcessExpression=https://lrclib.com/api/get/%Value
DataArtist.StartTags="artistName":"
DataArtist.FinishTags=",
DataAlbum.StartTags="albumName":"
DataAlbum.FinishTags=",
DataLyrics.StartTags="syncedLyrics":"
DataLyrics.FinishTags=",

[ly.synced-musixmatch.com]
Class=TAIMPLyricsWebPageBasedProvider
CustomHeaders=\nCookie: AWSELBCORS=0; AWSELB=0
; Clone and setup repository, then run php artisan usertoken and copy generated token to replace <MX_TOKEN_X>
SearchQuery=https://apic-desktop.musixmatch.com/ws/1.1/track.search?user_language=en&app_id=web-desktop-app-v1.0&usertoken=<MX_TOKEN_1>&q_track=%title%&q_artist=%artist%&f_has_subtitle=1&page_size=2
SearchQueryEncoding=URL
SearchResult.StartTags="track_list":[
SearchResult.FinishTags=]}}}
SearchResultArtist.StartTags="artist_name":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="track_name":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="commontrack_id":
SearchResultURL.FinishTags=,
; Do not use same token for every Musixmatch URLs
SearchResultURL.PostProcessExpression=https://apic-desktop.musixmatch.com/ws/1.1/track.subtitle.get?user_language=en&app_id=web-desktop-app-v1.0&usertoken=<MX_TOKEN_2>&commontrack_id=%Value
DataLyrics.StartTags="subtitle_body":"
DataLyrics.FinishTags=",

[ly.music.163.com]
Class=TAIMPLyricsWebPageBasedProvider
;CustomHeaders=\ncontent-type: application/json; charset=utf-8
SearchQuery=https://music.163.com/api/cloudsearch/pc/?type=1&s=%title%%20%artist%&limit=5&offset=0
SearchQueryEncoding=URL
SearchResult.StartTags="songs":[
SearchResult.FinishTags=]
SearchResultArtist.StartTags="ar":[{"name":"
SearchResultArtist.FinishTags="
SearchResultTitle.StartTags="name":"
SearchResultTitle.FinishTags="
SearchResultURL.StartTags="id":
SearchResultURL.FinishTags=,
SearchResultURL.PostProcessExpression=https://music.163.com/api/song/lyric?os=pc&id=%Value&lv=1
DataLyrics.StartTags="lyric":"
DataLyrics.FinishTags="}
DataLyrics.PostProcessExpression=%StrTrim(%IFEqual(%StrPos(%Char(20316),%IFEqual(%StrPos(%Char(20316),%Value),0,%Value,%StrCopy(%Value,%StrPos(%Char(10),%Value),%Length(%Value)))),0,%IFEqual(%StrPos(%Char(20316),%Value),0,%Value,%StrCopy(%Value,%StrPos(%Char(10),%Value),%Length(%Value))),%StrCopy(%IFEqual(%StrPos(%Char(20316),%Value),0,%Value,%StrCopy(%Value,%StrPos(%Char(10),%Value),%Length(%Value))),%StrPos(%Char(10),%StrTrim(%IFEqual(%StrPos(%Char(20316),%Value),0,%Value,%StrCopy(%Value,%StrPos(%Char(10),%Value),%Length(%Value))))),%Length(%Value))))

[ly.spotify-paxsenix.org]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://lyrics.paxsenix.org/spotify/search?q=%artist%%20%title%
SearchQueryEncoding=URL
SearchResultMaxCount=2
SearchResult.StartTags={
SearchResult.FinishTags=}
SearchResultArtist.StartTags="artistName":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="name":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="trackId":"
SearchResultURL.FinishTags=",
; Do not use same token as above
SearchResultURL.PostProcessExpression=https://apic-desktop.musixmatch.com/ws/1.1/macro.subtitles.get?format=json&namespace=lyrics_richsynched&app_id=web-desktop-app-v1.0&usertoken=<MX_TOKEN_3>&track_spotify_id=%Value
DataLyrics.StartTags="subtitle_body":"
DataLyrics.FinishTags=",

[ly.kugou.com]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=http://mobilecdn.kugou.com/api/v3/search/song?format=json&keyword=%artist%%20%title%&pagesize=3&showtype=1
SearchQueryEncoding=URL
SearchResult.StartTags="info":[
SearchResult.FinishTags=],
SearchResultArtist.StartTags="singername":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="songname":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="hash":"
SearchResultURL.FinishTags=",
SearchResultURL.PostProcessExpression=https://andrechris24.serv00.net/kugou/aimp/%Value
DataLyrics.StartTags="lyric":"
DataLyrics.FinishTags="}
DataLyrics.PostProcessExpression=%Replace(%Value,\/,/)

[ly.qq.serv00.net]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://andrechris24.serv00.net/qqmusic/results?query=%artist%%20%title%
SearchQueryEncoding=URL
SearchResultMaxCount=3
SearchResult.StartTags=<a class="list-group-item list-group-item-action"
SearchResult.FinishTags=</a>
SearchResultArtist.StartTags=data-artist="
SearchResultArtist.FinishTags="
SearchResultTitle.StartTags=data-title="
SearchResultTitle.FinishTags="
SearchResultURL.StartTags=data-id="
SearchResultURL.FinishTags="
SearchResultURL.PostProcessExpression=https://andrechris24.serv00.net/qqmusic/%Value
DataLyrics.StartTags="lyric":"
DataLyrics.FinishTags=",

[ly.bandcamp.com]
Class=TAIMPLyricsWebPageBasedProvider
CustomHeaders=User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
SearchQuery=https://bandcamp.com/search?q=%artist%%20%title%&item_type=t
SearchQueryEncoding=URL
SearchResultMaxCount=3
SearchResult.StartTags=class="searchresult data-search"|>
SearchResult.FinishTags=</li>
SearchResultArtist.StartTags=class="subhead">|by 
SearchResultArtist.FinishTags=</div>
SearchResultTitle.StartTags=a href=|>
SearchResultTitle.FinishTags=</a>
SearchResultURL.StartTags=a href="
SearchResultURL.FinishTags="
DataLyrics.StartTags=class="tralbumData lyricsText">
DataLyrics.FinishTags=</div>

[ly.genius.com]
Class=TAIMPLyricsWebPageBasedProvider
CustomHeaders=\ncontent-type: application/json; charset=utf-8\ncontent-encoding: gzip\nuser-agent: Mozilla/5.0 (Android 13; Mobile; rv:68.0) Gecko/68.0 Firefox/105.0
SearchQuery=https://genius.com/api/search/song?per_page=5&q=%artist%+%title%
SearchQueryEncoding=URL
SearchResult.StartTags="hits":[
SearchResult.FinishTags=],"next_page"
SearchResultArtist.StartTags="name":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="title":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="url":"
SearchResultURL.FinishTags=",
DataLyrics.StartTags=data-lyrics-container="true"|</h2>
DataLyrics.FinishTags=<div class="LyricsFooter

[ly.plain-lrclib.net]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://lrclib.net/api/search?artist_name=%artist%&track_name=%title%
SearchQueryEncoding=URL
SearchResultMaxCount=5
SearchResult.StartTags=[
SearchResult.FinishTags=]
SearchResultArtist.StartTags="artistName":"
SearchResultArtist.FinishTags="
SearchResultTitle.StartTags="trackName":"
SearchResultTitle.FinishTags="
SearchResultURL.StartTags="id":
SearchResultURL.FinishTags=,
SearchResultURL.PostProcessExpression=https://lrclib.com/api/get/%Value
DataArtist.StartTags="artistName":"
DataArtist.FinishTags=",
DataLyrics.StartTags="plainLyrics":"
DataLyrics.FinishTags=",

[ly.plain-musixmatch.com]
Class=TAIMPLyricsWebPageBasedProvider
CustomHeaders=\nCookie: AWSELBCORS=0; AWSELB=0
; Do not use same token as above or in env
SearchQuery=https://apic-desktop.musixmatch.com/ws/1.1/track.search?user_language=en&app_id=web-desktop-app-v1.0&usertoken=<MX_TOKEN_4>&q_track=%title%&q_artist=%artist%&f_has_lyrics=1&page_size=2
SearchQueryEncoding=URL
SearchResult.StartTags="track_list":[
SearchResult.FinishTags=]}}}
SearchResultArtist.StartTags="artist_name":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="track_name":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="commontrack_id":
SearchResultURL.FinishTags=,
SearchResultURL.PostProcessExpression=https://apic-desktop.musixmatch.com/ws/1.1/track.lyrics.get?user_language=en&app_id=web-desktop-app-v1.0&usertoken=<MX_TOKEN_5>&commontrack_id=%Value
DataLyrics.StartTags="lyrics_body":"
DataLyrics.FinishTags=",

[ly.songlyrics2.com]
Class=TAIMPLyricsWebPageBasedProvider
CustomHeaders=User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
SearchQuery=http://www.songlyrics.com/index.php?section=search&searchW=%artist%:%title%&submit=Search
SearchResultMaxCount=3
SearchResult.StartTags=div class="serpresult"
SearchResult.FinishTags=</div>
SearchResultArtist.StartTags=serpdesc-2|by|>
SearchResultArtist.FinishTags=</a>
SearchResultTitle.StartTags=title="
SearchResultTitle.FinishTags="
SearchResultURL.StartTags=<a href="
SearchResultURL.FinishTags=" title="
DataArtist.StartTags=Artist: |">
DataArtist.FinishTags=</p>|</a>
DataAlbum.StartTags=Album: |">
DataAlbum.FinishTags=</p>|</a>
DataLyrics.StartTags=id="songLyricsDiv-outer">|iComment-text">
DataLyrics.FinishTags=</div>|</p>
DataLyrics.PostProcessExpression=%IFGreater(%Length(%Value),100,%Value,)

[ly.songlyrics.com]
Class=TAIMPLyricsWebPageBasedProvider
CustomHeaders=User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
SearchQuery=http://www.songlyrics.com/index.php?section=search&searchW=%artist%+-+%title%&submit=Search
SearchQueryEncoding=URL
SearchResult.StartTags=<div class="serpresult">
SearchResult.FinishTags=<div class="serpdesc-2">
SearchResultTitle.StartTags=title="
SearchResultTitle.FinishTags="
SearchResultArtist.StartTags=alt="
SearchResultArtist.FinishTags="
SearchResultURL.StartTags=<a href="
SearchResultURL.FinishTags="
DataLyrics.StartTags=<p id="songLyricsDiv"|iComment-text">
DataLyrics.FinishTags=</p>
DataLyrics.PostProcessExpression=%IFGreater(%Length(%Value),100,%Value,)

[ly.mldb.org]
Class=TAIMPLyricsWebPageBasedProvider
Compliance=60
CustomHeaders=User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
SearchQuery=https://www.mldb.org/search?mq=%artist%+-+%title%&si=0&mm=0&ob=1&btnI=I%27m+Feeling+Lucky
DataLyrics.StartTags=<p class="songtext"|>
DataLyrics.FinishTags=</table>|</p>
DataArtist.StartTags=class="centerplane"|<a href='artist-|>
DataArtist.FinishTags=</body>|</td>|</a>
DataAlbum.StartTags=class="centerplane"|<a href="album-|>
DataAlbum.FinishTags=</body>|</td>|</a>
DataTitle.StartTags=class="centerplane"|<h1>
DataTitle.FinishTags=</h1>|<span

[ly.plain-deezer.com]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://api.deezer.com/search/track?limit=3&q=%artist%%20%title%
SearchQueryEncoding=URL
SearchResult.StartTags="data":[
SearchResult.FinishTags=],
SearchResultArtist.StartTags="artist":{|"name":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="title":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="id":
SearchResultURL.FinishTags=,
SearchResultURL.PostProcessExpression=https://lyrics.paxsenix.org/deezer/lyrics?id=%Value
DataLyrics.StartTags="plain_lyrics":"
DataLyrics.FinishTags=",
DataLyrics.PostProcessExpression=%IFGreater(%Length(%Value),28,%Value,)

[ly.plain-apple.com]
Class=TAIMPLyricsWebPageBasedProvider
SearchQuery=https://itunes.apple.com/search?term=%artist%%20%title%&entity=song&limit=3
SearchQueryEncoding=URL
SearchResult.StartTags="results":[
SearchResult.FinishTags=]}
SearchResultArtist.StartTags="artistName":"
SearchResultArtist.FinishTags=",
SearchResultTitle.StartTags="trackName":"
SearchResultTitle.FinishTags=",
SearchResultURL.StartTags="trackId":"
SearchResultURL.FinishTags=",
SearchResultURL.PostProcessExpression=https://lyrics.paxsenix.org/apple-music/lyrics?id=%Value
DataLyrics.StartTags="plain":"
DataLyrics.FinishTags=",
DataLyrics.PostProcessExpression=%IFGreater(%Length(%Value),28,%Value,)

[aa.track.apple.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://music.apple.com/id/search?term=%artist%%20%title%
SearchQueryEncoding=URL
SearchResult.StartTags=data-testid="track-lockup"
SearchResult.FinishTags=track-lockup__context-menu
SearchResultTitle.StartTags=data-testid="track-lockup-title">
SearchResultTitle.FinishTags=</li>
SearchResultArtist.StartTags=data-testid="track-lockup-subtitle">
SearchResultArtist.FinishTags=</span>
SearchResultAlbumArt.StartTags=<source sizes="|srcset="
SearchResultAlbumArt.FinishTags=/48x48
SearchResultAlbumArt.PostProcessExpression=%Value/1200x1200bb.jpg

[aa.album.apple.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://music.apple.com/id/search?term=%artist%%20%album%
SearchQueryEncoding=URL
SearchResult.StartTags=data-testid="product-lockup"
SearchResult.FinishTags=</li>
SearchResultAlbum.StartTags=data-testid="product-lockup-title">
SearchResultAlbum.FinishTags=</span>
SearchResultArtist.StartTags=data-testid="product-lockup-subtitle">
SearchResultArtist.FinishTags=</a>
SearchResultAlbumArt.StartTags=<source sizes="|srcset="
SearchResultAlbumArt.FinishTags=/296x296
SearchResultAlbumArt.PostProcessExpression=%Value/1200x1200bb.jpg

[aa.better.apple.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://music.apple.com/id/search?term=%artist%%20-%20%title%
SearchQueryEncoding=URL
SearchResult.StartTags=<picture class="
SearchResult.FinishTags=<span aria-label="MORE"
SearchResultTitle.StartTags=data-testid="top-search-result-title">|>
SearchResultTitle.FinishTags=</span>
SearchResultArtist.StartTags=data-testid="top-search-result-subtitle">Song|%Char(183)
SearchResultArtist.FinishTags=</li>
SearchResultArtist.PostProcessExpression=%StrTrim(%Value)
SearchResultAlbumArt.StartTags=<source sizes="|srcset="
SearchResultAlbumArt.FinishTags=.jpg/
SearchResultAlbumArt.PostProcessExpression=%Value.jpg/1200x1200bb.jpg

[aa.deezer.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://api.deezer.com/2.0/search/album?q=%artist%+%20+%album%
SearchQueryEncoding=URL
SearchResult.StartTags={
SearchResult.FinishTags=}
SearchResultArtist.StartTags="name"|"
SearchResultArtist.FinishTags=,|"
SearchResultAlbum.StartTags="title"|"
SearchResultAlbum.FinishTags=,|"
SearchResultAlbumArt.StartTags="cover_big"|"
SearchResultAlbumArt.FinishTags=,|"
SearchResultAlbumArt.PostProcessExpression=%Replace(%Value,\/,/)

[aa.bandcamp.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://bandcamp.com/search?q=%album%&item_type=a
SearchQueryEncoding=URL
SearchResult.StartTags=class="searchresult data-search"|>
SearchResult.FinishTags=</li>
SearchResultArtist.StartTags=class="subhead">|by 
SearchResultArtist.FinishTags=</div>
SearchResultAlbum.StartTags=a href=|>
SearchResultAlbum.FinishTags=</a>
SearchResultAlbumArt.StartTags=img src="
SearchResultAlbumArt.FinishTags="
SearchResultAlbumArt.PostProcessExpression=%Replace(%Replace(%Value,f4.,f1.),_7.,_10.)

[aa.discogs.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://www.discogs.com/en/search/?q=%artist%+-+%title%&type=all&type=all
SearchQueryEncoding=URL
SearchResult.StartTags=cards cards_layout_large
SearchResult.FinishTags=card_actions skittles
SearchResultArtist.StartTags=card-artist-name|<span title="|<a|>
SearchResultArtist.FinishTags=</span|</a
SearchResultAlbum.StartTags=card-release-title|<a|>
SearchResultAlbum.FinishTags=</div|</a
SearchResultAlbumArt.StartTags=<img data-src="
SearchResultAlbumArt.FinishTags="

[aa.amazon.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://www.amazon.com/s?k=%artist%+%20+-+%20+%title%&i=digital-music
SearchResult.StartTags=<div class="a-section">
SearchResult.FinishTags=<div data-asin
SearchResultArtist.StartTags=>by |<span|>
SearchResultArtist.FinishTags=</div|</span>
SearchResultAlbum.StartTags=<h2 class="|<span|>
SearchResultAlbum.FinishTags=</h2|</span
SearchResultAlbumArt.StartTags=<img|src="
SearchResultAlbumArt.FinishTags=>|"

[aa.genius.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://genius.com/api/search/multi?per_page=5&q=%artist%%20%title%
CustomHeaders=\ncontent-type: application/json; charset=utf-8
;SearchQueryEncoding=URL
SearchResult.StartTags={"highlights"
SearchResult.FinishTags=}}]}
SearchResultArtist.StartTags="artist_names":"
SearchResultArtist.FinishTags="
SearchResultArtist.PostProcessExpression=%StrLeft(%StrLeft(%StrLeft(%Value,%Char(44)),%Char(40)),%Char(41)))
SearchResultTitle.StartTags="title":"
SearchResultTitle.FinishTags="
SearchResultTitle.PostProcessExpression=%StrLeft(%StrLeft(%StrLeft(%Value,%Char(44)),%Char(40)),%Char(41)))
SearchResultAlbumArt.StartTags="song_art_image_url":"
SearchResultAlbumArt.FinishTags="
;SearchResultAlbumArt.PostProcessExpression=%IFEqual(%Value,https://assets.genius.com/images/default_cover_image.png?1676573542,,%Value)

[aa.spotify.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://lyrics.paxsenix.org/spotify?q=%artist%%20%title%
SearchResult.StartTags=[
SearchResult.FinishTags=]
SearchResultArtist.StartTags="artistName":"
SearchResultArtist.FinishTags="
SearchResultTitle.StartTags="name":"
SearchResultTitle.FinishTags="
SearchResultAlbumArt.StartTags="albumCover":"
SearchResultAlbumArt.FinishTags="

[aa.itunes.com]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=http://itunes.apple.com/search?entity=album&term=%artist%+%20+%album%
SearchQueryEncoding=URL
SearchResult.StartTags={
SearchResult.FinishTags=}
SearchResultArtist.StartTags="artistName"|"
SearchResultArtist.FinishTags=,|"
SearchResultAlbum.StartTags="collectionName"|"
SearchResultAlbum.FinishTags=,|"
SearchResultAlbumArt.StartTags="artworkUrl100"|"
SearchResultAlbumArt.FinishTags=,|"
SearchResultAlbumArt.PostProcessExpression=%Replace(%Value,100x100bb.jpg,600x600-75.jpg)

[aa.last.fm]
Class=TAIMPAlbumArtWebPageBasedProvider
SearchQuery=https://www.last.fm/search/albums?q=%artist%+-+%album%
SearchResult.StartTags=album-result-inner
SearchResult.FinishTags=</div>
SearchResultArtist.StartTags=album-result-artist|<a|>
SearchResultArtist.FinishTags=</p|</a
SearchResultTitle.StartTags=class="title"|span>
SearchResultTitle.FinishTags=</span
SearchResultAlbumArt.StartTags=album-result-image|src="
SearchResultAlbumArt.FinishTags=</a|"
SearchResultAlbumArt.PostProcessExpression=%IF(%StrPos(c6f59c1e5e7240a4c0d427abd71f3dbb,%Value),,%Replace(%Value,/64s/,/ar0/))
